authors:
  nitya:
    name: Nitya Narasimhan
    description: AI Advocate, Microsoft
    avatar: https://github.com/nitya.png
  sharda:
    name: Sharda Kaur
    description: MLSA Gold 
    avatar: https://github.com/shardakaurr.png